### ISSUE TITLE
Web hosting of output shouldnt be in randomly generated directories

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-Climate/acme_workflow#1]
Currently the directories for holding output to be hosted are copied into directories with randomly generated names to avoid collisions, but this leads to confusion when users to try and find their output. This should be changed so that when the user specifies a location, the output is copied into that specific directory.

**Comment by golaz** [comment]
In the configuration file, define the following:

```
[global]

host_directory = /var/www/acme/golaz1
```

and then for each diagnostics package, something

```
[amwg]

host_prefix = amwg
```

The final directory should be

```
/var/www/acme/golaz1/amwg/YR01-YR02
```

Also, make sure the permissions of the web files are set properly. World readable for files, world readable and executable for directories.

**Comment by mccoy20** [comment]
The final directory should also include the experiment name, like that:
  /var/www/acme/golaz1/experiment_name/amwg/YR01-YR02

**Comment by sterlingbaldwin** [comment]
Are you sure you want it like that @mccoy20? If CIME goes back to making all experiments equal case_scripts, or if a user ever has two experiments with the same name, they will overwrite each other.

**Comment by mccoy20** [comment]
Without it, it will overwrite the results as well. Your tool should be smarter then the user and check if the directory exists and either ask for confirmation or create a new directory with for example '_1' or something like that. If later on the user decides he really wanted the same directory, he can delete the old one and possibly rename the new one, just created. When checking for the plots, the user will be looking for the experiment first then the results for a given diagnostics and then the year, hence the ordering of directories.

**Comment by sterlingbaldwin** [comment]
The new version is being tested right now, but so far its working. The new format for accessing the data via browser is:

    https://<SERVER>/<USER>/<EXPERIMENT>/<DIAGNOSTIC>/<START_YEAR>-<END_YEAR>

for example (these will 404 until the tests finish):
    https://acme-viewer.llnl.gov/baldwin32/case_scripts/amwg/0001-0005
    https://acme-viewer.llnl.gov/baldwin32/case_scripts/coupled_diag/0001-0005

For the time being I didnt want to replace the current script with the new one until its finished being tested, so the new version can be found at 

     /p/cscratch/acme/bin/acme_workflow_2

The run.cfg has changed very slightly, so old configs wont work with the new version. The change is very small, and just adds 

    host_directory
    host_url_prefix

to each job. This allows the user to specify the url and the path for each job, in the case of acme1 these can be the same (simply the name of the job), but I wanted to differentiate them so that if apache was setup to server from a specific location it would work.

A new copy of a default config is in the acme_workflow_2 directory.
