### ISSUE TITLE
Year set names should be more descriptive.

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-Climate/acme_workflow#2]
Instead of naming directories that hold output after the set number (year_set_1, year_set_2), they should be named after the years that make up the set (0001-10, 0010-20).

**Comment by golaz** [comment]
Better to use for digits for both years: 0001-0010 and 0010-0020. Someday, we may want to process in 100 year chunk: 0001-0100.

**Comment by sterlingbaldwin** [comment]
This is done in the latest version.
